version: '3.8'

services:
  auth-service:
    build: ./app/auth-service
    ports:
      - "${AUTH_SERVICE_PORT:-3003}:${AUTH_SERVICE_PORT:-3003}"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
    networks:
      - microservices-network

  user-service:
    build: ./app/user-service
    ports:
      - "${USER_SERVICE_PORT:-3001}:${USER_SERVICE_PORT:-3001}"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
    networks:
      - microservices-network

  order-service:
    build: ./app/order-service
    ports:
      - "${ORDER_SERVICE_PORT:-3002}:${ORDER_SERVICE_PORT:-3002}"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
    networks:
      - microservices-network

  nginx:
    image: nginx:alpine
    ports:
      - "${GATEWAY_PORT:-3000}:80"
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - user-service
      - order-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge